/*
 * msg_proc.c: implementation of the
 * remote procedure "printmessage"
 */
#include <stdio.h>
#include "msg.h" //msg.h generated by rpcgen
 
int * printmessage_1_svc(char **msg, struct svc_req *req) {
	// must be static! 
	static int result;			
	printf("Console:%s\n", *msg);
	result = 0;
	return (&result);
}