/*
 * rprintmsg.c: remote version
 * of "printmsg.c"
 */
#include <stdio.h>
#include <string.h>
#include "msg.h" // msg.h generated by rpcgen
#define RPC_PROGRAM MsgRPC
#define RPC_PRG_VER MsgRPC_Ver_1

void printHelp(char *cmd) {
	printf("usage: %s host action [options]\n", cmd);

	printf("\n========action list======\n");

	printf("a: boundle a application\n");
	printf("b: unbundle a application\n");
	printf("t: talk to rpc server - t message\n");
	// printf("c: send a notification\n");
	// printf("l: list all app in app list\n");
	// printf("r: change mobole ip to redirect\n");
	// printf("R: change PS IP to redirect\n");
	// printf("s: suspend push notification\n");
	// printf("o: resume push notification\n");
	// printf("v: get hpns config info\n");
	// printf("q: query regId from PE via appID\n");
	// printf("p: change to polling connect mode\n");
	// printf("P: change to auto connect mode\n");
	// printf("M: change to manual connect mode\n");
}

int talk_to_server(char *server, char* msg) {
	CLIENT *clnt;
	int *result;
	/*
	 * Create client "handle" used for 
	 * calling procedure on the server
	 * designated on the command line.
	 */
	clnt = clnt_create(server, RPC_PROGRAM, RPC_PRG_VER, "tcp");
	if (clnt == (CLIENT *)NULL) {
		/*
		 * Couldn't establish connection
		 * with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(server);
		return 1;
	}

	/*
     * Call the remote procedure
     * "printmessage" on the server
     */
	result = printmessage_1(&msg, clnt);
	if (result == (int *)NULL) {
		/*
		 * An error occurred while calling 
	     * the server.
		 * Print error message and die.
		 */
		clnt_perror(clnt, server);
		return 1;
	}
	clnt_destroy( clnt );
	return 0;
}

int shutdown_server(char *server) {
	CLIENT *clnt;
	int *result;
	/*
	 * Create client "handle" used for 
	 * calling procedure on the server
	 * designated on the command line.
	 */
	clnt = clnt_create(server, RPC_PROGRAM, RPC_PRG_VER, "tcp");
	if (clnt == (CLIENT *)NULL) {
		/*
		 * Couldn't establish connection
		 * with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(server);
		return 1;
	}

	/*
     * Call the remote procedure
     */
	stop_1(NULL,clnt);
	clnt_destroy( clnt );
	return 0;
}


int main(int argc, char *argv[]) {
	
	char *server;
	char action;

	if (argc < 3 || strlen(argv[2])!=1) {
		// fprintf(stderr, "usage: %s host message\n", argv[0]);
		printHelp(argv[0]);
		return 1;
	}

	server = argv[1];
	action = argv[2][0];

	switch(action) {
		case 's':
			shutdown_server(server);
			printf("Shutdown Server.\n");
			break;
		case 't':
			if (argc !=4 || talk_to_server(server, argv[3]))
			{
				/* code */
				printf("failed of invalid input or check the output above.\n");
				return 1;
			}
	
			break;
		default:
			fprintf(stderr, "%s: can not recognize your action %c\n",argv[0], action);
			break;
	}



	/* list server suport actions */
	// char **actions = list_actions_1(NULL,clnt);
	// if (actions == NULL) {
	// 	clnt_perror(clnt, server);
	// 	return 1;
	// }
	// printf("Server Info\n%s\n", *actions);

	printf("Called on %s\n", server);
	
	return 0;
}