/*
 * rprintmsg.c: remote version
 * of "printmsg.c"
 */
#include <stdio.h>
#include "msg.h" // msg.h generated by rpcgen

int main(int argc, char *argv[]) {
	CLIENT *clnt;
	int *result;
	char *server;
	char *message;

	if (argc != 3) {
		fprintf(stderr, "usage: %s host message\n", argv[0]);
		return 1;
	}

	server = argv[1];
	message = argv[2];
/*
 * Create client "handle" used for 
 * calling MESSAGEPROG on the server
 * designated on the command line.
 */
 clnt = clnt_create(server, MESSAGEPROG, PRINTMESSAGEVERS, "tcp");
 if (clnt == (CLIENT *)NULL) {
	/*
	 * Couldn't establish connection
     * with server.
	 * Print error message and die.
	 */
	 clnt_pcreateerror(server);
	 return 1;
	}
	/*
     * Call the remote procedure
     * "printmessage" on the server
     */
	result = printmessage_1(&message, clnt);
	if (result == (int *)NULL) {
		/*
		 * An error occurred while calling 
	     * the server.
		 * Print error message and die.
		 */
		clnt_perror(clnt, server);
		return 1;
	}

	/* The message got printed on the
     * server's console
     */
	printf("Message delivered to %s\n", server);
	//fprintf(stderr, "%s: could not print your message\n",argv[0]);
	clnt_destroy( clnt );
	return 0;
}